[package]
name = "saddle"
version = "0.1.1"
edition = "2024"
license = "Apache-2.0"
authors = ["Matilde Morrone <contact@morrone.dev>"]
description = "Async seat managment made easy"
readme = "README.md"
documentation = "https://docs.rs/saddle"
repository = "https://github.com/verdiwm/saddle"
include = ["src/**/*.rs", "README.md", "LICENSE"]

[dependencies]
rustix = { version = "1.1.2", features = ["fs"] }
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["signal"] }
tokio-stream = { version = "0.1.17", default-features = false }
tracing = "0.1.41"
zbus = { version = "5.11.0", default-features = false, features = ["tokio"] }

[dev-dependencies]
anyhow = "1.0.99"
tokio = { version = "1.47.1", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }
tracing-subscriber = { version = "0.3.20", features = [
    "env-filter",
    "tracing-log",
] }
colpetto = { version = "0.6.0", features = ["tokio", "helper", "tracing"] }
input-linux-sys = "0.9.0"

[patch.crates-io]
# colpetto = { git = "https://github.com/verdiwm/colpetto" }
# colpetto = { path = "../colpetto" }
